apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapp-deployment
  labels:
    app: restapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restapp
  template:
    metadata:
      labels:
        app: restapp
    spec:
      containers:
      - name: restapp-container
        image: meeradevi/docker_task:new
        ports:
        - containerPort: 8080
